## Общая Информация

### Описание проекта:
    Заказчик GoProtect. Компания занимается развитием сервиса "Мой Чемпион". Цель сервиса помочь спортивным школам фигурного катания и тренерам мониторить прогресс спортсменов с целью дальнейшего их развития.

### Цель:
    Создать решение матчинга названий спортивных школ с эталонными названиями этих школ.
    Одна и та же школа может быть записана по-разному. Например:
       - Республика Татарстан, СШОР Авиатор
       - республика татарстан, "Авиатор"
       - МБУ ДО СШОР "Авиатор", Республика Татарстан

## Загрузка данных

In [1]:
#!pip install -U sentence-transformers
#!pip freeze > requirements.txt

#!pip install -r requirements.txt

In [2]:
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sentence_transformers import (
    SentenceTransformer,
    InputExample,
    util, losses
)

pd.set_option('display.max_row', None)
pd.options.display.float_format = '{:.2f}'.format

In [3]:
user_imput_name = pd.read_csv('Примерное написание.csv')
user_imput_name.head()

   school_id                                               name
0       1836                                       ООО "Триумф"
1       1836                                Москва, СК "Триумф"
2        610                             СШОР "Надежда Губернии
3        610  Саратовская область, ГБУСО "СШОР "Надежда Губе...
4        609                                     "СШ "Гвоздика"

In [4]:
name_school = pd.read_csv('Школы.csv')
name_school.head()

   school_id                  name                region
0          1              Авангард    Московская область
1          2              Авангард     Ямало-Ненецкий АО
2          3               Авиатор  Республика Татарстан
3          4                Аврора       Санкт-Петербург
4          5  Ice Dream / Айс Дрим       Санкт-Петербург

**Вывод:**
- Подготовить данные. Очистить от знаков припинания
- На основе эталонного датасета подготовить обучающий набор данных за счет аугментации.

## Подготовка данных

In [5]:
def cleaning_txt(df:pd.DataFrame)->pd.DataFrame:
    """ Функция на вход получает объект DataFrame с названием спортивных школ и удаляет все лишние знаки.
    """
    
    data = df.copy()
    data['name'] = (
        data['name']
        .replace(r'[^А-Яа-яёЁA-Za-z\s\d]', ' ', regex=True)
        .replace(r'(\s\w{1,2}\s ^[им.\sА-Я.А-Я.])|(\bг\s)', ' ', regex=True)
        .replace(r'\s+', ' ', regex=True)
    )
    
    return data

In [6]:
df = cleaning_txt(user_imput_name)
df.head()

   school_id                                              name
0       1836                                       ООО Триумф
1       1836                                 Москва СК Триумф
2        610                             СШОР Надежда Губернии
3        610  Саратовская область ГБУСО СШОР Надежда Губернии
4        609                                      СШ Гвоздика

In [7]:
def augmentation(data:pd.DataFrame, N:int=5, alpha:float=.3):

    """Функция получает на вход DataFrame и добавляет ошибки в
    alpha=.3 #допустимая доля ошибок в строке
    N=5 #кол-во циклов генерации ошибок"""

    df = data.copy()

    #словарь опечаток
    error = {'й':'12цыф', 'ц':'йфыву32', 'у':'кавыц34', 'к':'епаву45', 'е':'нрпак56', 
             'н':'горпе67', 'г':'шорн78', 'ш':'щдлог89', 'щ':'зждлш90', 'з':'хэждщ0-', 'х':'ъэжз-=',
             'ъ':'ёэх=', 'ё':'ъ', 'ф':'йцычя', 'ы':'вчяфйцу', 'в':'асчыук', 'а':'пмсвке', 'п':'римакен',
             'р':'отипнг', 'о':'лшгнрть', 'л':'дбьошщ', 'д':'жюблщз', 'ж':'э/юдзх', 'э':'ъ/жх',
             'я':'фыч', 'ч':'с яыв', 'с':'м чва', 'м':'и сап', 'и':'т мпр', 'т':'ь иро', 'ь':'б тол',
             'б':'юьлд', 'ю':'/ждб', ' ':'чсмитьб', '1':'2й]', '2':'1йц3', '3':'4уц2', '4':'5ку3',
             '5':'6ек4', '6':'7не5', '7':'8гн6', '8':'9шг7', '9':'0щш8', '0':'-зщ9', '-':'0зх=',
             '=':'-хъ', '_':'0зх=', '+':'-_хъ', 'q':'12wsa', 'w':'2qasde3', 'e':'3wsdfr4', 'r':'4edfgt5',
             't':'5rfghy6', 'y':'6tghju7', 'u':'ikjhy78', 'i':'olkju89', 'o':'p;lki90', 'p':'[;lo0-',
             'a':'szqw', 's':'dxzaqwe', 'd':'fcxswer', 'f':'gvdrt', 'g':'hbvfty', 'h':'jnbgyu',
             'j':'kmnhui', 'k':'l,mjio', 'l':';.,kop', 'z':'xsa', 'x':'cdsaz', 'c':'v xdf', 'v':'b cfg',
             'b':'n vgh', 'n':'m bhj', 'm':', njk<'}
    
    col = ['name', 'region']
    col2= ['region', 'name']

    #вложенный список списков всех преобразований
    aug_list = df[col].apply(lambda row: [' '.join(row.astype(str))], axis=1) 

    tmp = df[col2].apply(lambda row: ' '.join(row.astype(str)), axis=1)
    _ = [aug_list[i].append(tmp[i]) for i in range(len(tmp))]

    for i in range(len(df)):
        school = aug_list[i]

        #список индексов ошибок
        ind = []

        #составляем список уникальных индексов
        while (len(set(ind)) < N) & (len(ind)/len(school[0]) < alpha):
            ind.append(np.random.randint(len(school[0])))
            ind = list(set(ind))

        #Инициализируем список типов ошибок
        # 1) Опечатка на клавиатуре
        # 2) Перестановка местами соседних символов
        # 3) Опечатка на клавиатуре с заменой на противоположный регистр
        n_error = list(np.random.randint(low=1, high=4, size=len(ind)))

        #список с прибавлением ошибок к предыдущей строке
        all_error = []

        for k in range(len(ind)):
            twu_list = list(school[0])

            if n_error[k] == 1:
                if twu_list[ind[k]].isupper():
                    try:
                        ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                        twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error].upper()
                    except:
                        ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                        twu_list[-1] = error.get(twu_list[-1].lower())[ind_error].upper()
                    finally:
                        aug_list[i].append(''.join(twu_list))
                        
                    if len(aug_list[i]) == 3:
                        pass
                    elif len(aug_list[i]) == 4:
                        twu_list = list(aug_list[i][-2])
                        try:
                            ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                            twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error].upper()
                        except:
                            ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                            twu_list[-1] = error.get(twu_list[-1].lower())[ind_error].upper()
                        finally:
                            all_error.append(''.join(twu_list))
                            aug_list[i].append(all_error[-1])
                    else:
                        twu_list = list(all_error[-1])
                        try:
                            ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                            twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error].upper()
                        except:
                            ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                            twu_list[-1] = error.get(twu_list[-1].lower())[ind_error].upper()
                        finally:
                            all_error.append(''.join(twu_list))
                            aug_list[i].append(all_error[-1])

                else:
                    try:
                        ind_error = np.random.randint(len(error.get(twu_list[ind[k]])))
                        twu_list[ind[k]] = error.get(twu_list[ind[k]])[ind_error]
                    except:
                        ind_error = np.random.randint(len(error.get(twu_list[-1])))
                        twu_list[-1] = error.get(twu_list[-1])[ind_error]
                    finally:
                        aug_list[i].append(''.join(twu_list))
                    
                    if len(aug_list[i]) == 3:
                        pass
                    elif len(aug_list[i]) == 4:
                        twu_list = list(aug_list[i][-2])
                        try:
                            ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                            twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error]
                        except:
                            ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                            twu_list[-1] = error.get(twu_list[-1].lower())[ind_error]
                        finally:
                            all_error.append(''.join(twu_list))
                            aug_list[i].append(all_error[-1])
                    else:
                        twu_list = list(all_error[-1])
                        try:
                            ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                            twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error]
                        except:
                            ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                            twu_list[-1] = error.get(twu_list[-1].lower())[ind_error]
                        finally:
                            all_error.append(''.join(twu_list))
                            aug_list[i].append(all_error[-1])

            elif n_error[k] == 2:
                try:
                    twu_list[ind[k]], twu_list[ind[k]+1] = twu_list[ind[k]+1], twu_list[ind[k]]
                except:
                    twu_list[-1], twu_list[-2] = twu_list[-2], twu_list[-1]
                finally:
                    aug_list[i].append(''.join(twu_list))
                    
                if len(aug_list[i])==3:
                    pass
                elif len(aug_list[i])==4:
                    twu_list = list(aug_list[i][-2])
                    try:
                        twu_list[ind[k]], twu_list[ind[k]+1] = twu_list[ind[k]+1], twu_list[ind[k]]
                    except:
                        twu_list[-2], twu_list[-1] = twu_list[-1], twu_list[-2]
                    finally:
                        all_error.append(''.join(twu_list))
                        aug_list[i].append(all_error[-1])
                else:
                    twu_list = list(all_error[-1])
                    try:
                        twu_list[ind[k]], twu_list[ind[k]+1] = twu_list[ind[k]+1], twu_list[ind[k]]
                    except:
                        twu_list[-2], twu_list[-1] = twu_list[-1], twu_list[-2]
                    finally:
                        all_error.append(''.join(twu_list))
                        aug_list[i].append(all_error[-1])

            elif n_error[k] == 3:
                if twu_list[ind[k]].isupper():
                    try:
                        ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                        twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error]
                    except:
                        ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                        twu_list[-1] = error.get(twu_list[-1].lower())[ind_error]
                    finally:
                        aug_list[i].append(''.join(twu_list))
                    
                    if len(aug_list[i]) == 3:
                        pass
                    elif len(aug_list[i]) == 4:
                        twu_list = list(aug_list[i][-2])
                        try:
                            ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                            twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error]
                        except:
                            ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                            twu_list[-1] = error.get(twu_list[-1].lower())[ind_error]
                        finally:
                            all_error.append(''.join(twu_list))
                            aug_list[i].append(all_error[-1])
                    else:
                        twu_list = list(all_error[-1])
                        try:
                            ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                            twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error]
                        except:
                            ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                            twu_list[-1] = error.get(twu_list[-1].lower())[ind_error]
                        finally:
                            all_error.append(''.join(twu_list))
                            aug_list[i].append(all_error[-1])

                else:
                    try:
                        ind_error = np.random.randint(len(error.get(twu_list[ind[k]])))
                        twu_list[ind[k]] = error.get(twu_list[ind[k]])[ind_error].upper()
                    except:
                        ind_error = np.random.randint(len(error.get(twu_list[-1])))
                        twu_list[-1] = error.get(twu_list[-1])[ind_error].upper()
                    finally:
                        aug_list[i].append(''.join(twu_list))
                    
                    if len(aug_list[i]) == 3:
                        pass
                    elif len(aug_list[i]) == 4:
                        twu_list = list(aug_list[i][-2])
                        try:
                            ind_error = np.random.randint(len(error.get(twu_list[ind[k]])))
                            twu_list[ind[k]] = error.get(twu_list[ind[k]])[ind_error].upper()
                        except:
                            ind_error = np.random.randint(len(error.get(twu_list[-1])))
                            twu_list[-1] = error.get(twu_list[-1])[ind_error].upper()
                        finally:
                            all_error.append(''.join(twu_list))
                            aug_list[i].append(all_error[-1])
                    else:
                        twu_list = list(all_error[-1])
                        try:
                            ind_error = np.random.randint(len(error.get(twu_list[ind[k]].lower())))
                            twu_list[ind[k]] = error.get(twu_list[ind[k]].lower())[ind_error].upper()
                        except:
                            ind_error = np.random.randint(len(error.get(twu_list[-1].lower())))
                            twu_list[-1] = error.get(twu_list[-1].lower())[ind_error].upper()
                        finally:
                            all_error.append(''.join(twu_list))
                            aug_list[i].append(all_error[-1])
                        
            else:
                try:
                    twu_list.pop(ind[k])
                except:
                    twu_list.pop(-1)
                finally:
                    aug_list[i].append(''.join(twu_list))
                
                if len(aug_list[i]) == 3:
                    pass
                elif len(aug_list[i]) == 4:
                    twu_list = list(aug_list[i][-2])
                    try:
                        twu_list.pop(ind[k])
                    except:
                        twu_list.pop(-1)
                    finally:
                        all_error.append(''.join(twu_list))
                        aug_list[i].append(all_error[-1])
                else:
                    twu_list = list(all_error[-1])
                    try:
                        twu_list.pop(ind[k])
                    except:
                        twu_list.pop(-1)
                    finally:
                        all_error.append(''.join(twu_list))
                        aug_list[i].append(all_error[-1])
                            
    df['aug'] = aug_list
    df['name'] = df[col].apply(lambda row: ' '.join(row.astype(str)), axis=1)

    df, df_aug = df, df.explode('aug')[['school_id', 'name','aug']].reset_index(drop=True)

    return df, df_aug

In [8]:
school, school_aug = augmentation(cleaning_txt(name_school), N=10)
school.head()

,school_id,name,region,aug
0,1,Авангард Московская область,Московская область,"[Авангард Московская область, Московская облас..."
1,2,Авангард Ямало-Ненецкий АО,Ямало-Ненецкий АО,"[Авангард Ямало-Ненецкий АО, Ямало-Ненецкий АО..."
2,3,Авиатор Республика Татарстан,Республика Татарстан,"[Авиатор Республика Татарстан, Республика Тата..."
3,4,Аврора Санкт-Петербург,Санкт-Петербург,"[Аврора Санкт-Петербург, Санкт-Петербург Аврор..."
4,5,Ice Dream Айс Дрим Санкт-Петербург,Санкт-Петербург,"[Ice Dream Айс Дрим Санкт-Петербург, Санкт-Пет..."

**Вывод:**
За счет аугментации увеличили датасет в пять раз добавив в этолонные названия школ ошибки.

## Обучение модели

In [9]:
def model(train, test):
    """Функция получает на вход тренировочный и тестовый DataFrame.
    Обучает модель и предсказывает school_id.
    Возвращает два объекта: 1)Словарь с accuracy для лучшего результата и топ5 результатов.
    2)Измененный тестовый DataFrame с предсказанными school_id"""
    
    train = train.copy()
    test = test.copy()
    
    model = SentenceTransformer('sentence-transformers/LaBSE')
    
    corpus = model.encode(train.name.values)
    query = model.encode(test.name.values)
    
    search_result = util.semantic_search(query, corpus, top_k=5)
    
    school_id = train.school_id.values
    predict_ind = [row[0]['corpus_id'] for row in search_result]
    test['predict_id'] = train.school_id.values[predict_ind]
    top_5 = [[row[x]['corpus_id'] for x in range(5)] for row in search_result]
    test['top_5_id'] = [[train.school_id[row[x]]for x in range(5)] for row in top_5]
    
    
    score = {
        'top':round((test.school_id == test.predict_id).mean(), 2),
        'top_5':round((test.apply(lambda x: x['school_id'] in  x['top_5_id'], axis=1)).mean(), 2)
    }
    
    return score, test

In [10]:
score, test = model(school, user_imput_name)

print('accuracy для top и top_5 результатов модели: ', score)
test.head()

accuracy для top и top_5 результатов модели:  {'top': 0.67, 'top_5': 0.92}

,school_id,name,predict_id,top_5_id
0,1836,"ООО ""Триумф""",1836,"[1836, 303, 225, 221, 135]"
1,1836,"Москва, СК ""Триумф""",1836,"[1836, 96, 303, 251, 104]"
2,610,"СШОР ""Надежда Губернии",610,"[610, 609, 183, 37, 24]"
3,610,"Саратовская область, ГБУСО ""СШОР ""Надежда Губе...",610,"[610, 37, 72, 194, 216]"
4,609,"""СШ ""Гвоздика""",609,"[609, 173, 181, 185, 610]"

## Вывод:
- Лучший результат модели показывает результат в 67% правильно предсказанных значений.
- В топ 5 результатов модели попадают 92% верно предсказанных school_id.
- Для улучшения результатов модели необходимо поработать с аугментацией обучающего датафрейма. Также до обучить модель на размеченном датафрейме на хорошие и плохие примеры.